name: master
on: [push]
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: npm test -- --ci --coverage --json --outputFile=test-results.json --testResultsProcessor="jest-junit"
      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.2.0
        with:
          filename: coverage/cobertura-coverage.xml
          badge: true
          format: 'markdown'
          output: 'both'

  publish:
    name: Publish package
    if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v3
      with:
        registry-url: 'https://registry.npmjs.org'
    - run: npm ci
    - run: npm publish
      continue-on-error: true
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
