name: Run tests

on: [push, pull_request]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: npx parcel build --no-source-maps --no-autoinstall
        env: 
          NODE_ENV: production
      - run: npm test -- --ci --coverage --json --outputFile=test-results.json --testResultsProcessor="jest-junit"
      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.2.0
        with:
          filename: coverage/cobertura-coverage.xml
          badge: true
          format: 'markdown'
          output: 'both'
